version: "3.8"
services:
  test-db:
    image: docker.io/library/mariadb:latest
    ports:
      - 5593:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    tmpfs:
      - /var/lib/mariadb