version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DBNAME: ${DB_DBNAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_PORT: ${BACKEND_PORT}
        VITE_BACKEND_HOST: ${BACKEND_HOST}
    ports:
      - ${FRONTEND_PORT}:80
  db:
    image: docker.io/library/mariadb:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      fish-db:/var/lib/mariadb
volumes:
  fish-db: