version: "3.8"
services:
  test-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    environment:
      JWT_SECRET: pTj+DBXRkyetocsvSTE1n4r95Gq8rCnCeKvl2qDNBDc=
      DB_HOST: test-db
    depends_on:
      - test-db
  test-db:
    image: docker.io/library/mariadb:latest
    ports:
      - 5593:5593
    environment:
      MYSQL_TCP_PORT: 5593
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    tmpfs:
      - /var/lib/mariadb